# Generated by Django 3.0.14 on 2022-06-03 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_productmutation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Product')),
                ('package', models.CharField(blank=True, db_column='ProductPackage', max_length=100, null=True)),
            ],
            options={
                'db_table': 'tblProduct',
                'managed': False,
            },
            bases=('product.product',),
        ),
    ]
