# Generated by Django 3.0.14 on 2022-06-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpackage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcontainedpackage',
            old_name='PCPPrice',
            new_name='pCPPrice',
        ),
        migrations.RenameField(
            model_name='productcontainedpackage',
            old_name='PCPQuantity',
            new_name='pCPQuantity',
        ),
        migrations.RenameField(
            model_name='productpackage',
            old_name='PackageCheckBox',
            new_name='packageIsSpecificPriceCheckBox',
        ),
        migrations.RenameField(
            model_name='productpackage',
            old_name='PackageName',
            new_name='packageName',
        ),
        migrations.RenameField(
            model_name='productpackage',
            old_name='PackagePrice',
            new_name='packagePrice',
        ),
        migrations.RenameField(
            model_name='productpackage',
            old_name='PackageType',
            new_name='packageType',
        ),
        migrations.RenameField(
            model_name='servicecontainedpackage',
            old_name='SCPPrice',
            new_name='sCPPrice',
        ),
        migrations.RenameField(
            model_name='servicecontainedpackage',
            old_name='SCPQuantity',
            new_name='sCPQuantity',
        ),
        migrations.RemoveField(
            model_name='productcontainedpackage',
            name='PCPDate',
        ),
        migrations.RemoveField(
            model_name='productpackage',
            name='PackageDate',
        ),
        migrations.RemoveField(
            model_name='servicecontainedpackage',
            name='SCPDate',
        ),
        migrations.AddField(
            model_name='productcontainedpackage',
            name='pCPCreateDate',
            field=models.DateTimeField(blank=True, db_column='PackageCreateDate', null=True),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='packageCreateDate',
            field=models.DateTimeField(blank=True, db_column='PackageCreateDate', null=True),
        ),
        migrations.AddField(
            model_name='servicecontainedpackage',
            name='sCPCreateDate',
            field=models.DateTimeField(blank=True, db_column='PackageCreateDate', null=True),
        ),
    ]
