# Generated by Django 3.0.14 on 2022-06-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpackage', '0002_auto_20220611_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackage',
            name='packageCreateDate',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='packageName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='packageType',
            field=models.CharField(max_length=20),
        ),
    ]
